import { useEffect, useMemo, useRef, useState } from 'react';
import { useSuspenseQuery } from '@tanstack/react-query';
import { Link, useSearch, useNavigate } from '@tanstack/react-router';
import { SlidersHorizontal, X, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ProductCard } from './ProductCard';
import type { Product } from '@/lib/catalog';
import { catalogQuery } from '@/lib/catalog-query';
const sorts=['Featured','Newest','Price: Low to High','Price: High to Low'];
export function CatalogPage({mode='shop'}:{mode?:'shop'|'search'}){
 const {products,categories,variants}=useSuspenseQuery(catalogQuery).data;const search=useSearch({strict:false}) as Record<string,string|undefined>;const navigate=useNavigate();const [filterOpen,setFilterOpen]=useState(false);const filterBtnRef=useRef<HTMLButtonElement>(null);const overlayRef=useRef<HTMLDivElement>(null);const trapTab=(e:KeyboardEvent,root:HTMLElement|null)=>{if(e.key!=='Tab'||!root)return;const els=[...root.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null);if(!els.length)return;const first=els[0];const last=els[els.length-1];if(!first||!last)return;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};useEffect(()=>{if(!filterOpen)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setFilterOpen(false);return}trapTab(e,overlayRef.current)};window.addEventListener('keydown',onKey);const prev=document.body.style.overflow;document.body.style.overflow='hidden';overlayRef.current?.focus();return ()=>{window.removeEventListener('keydown',onKey);document.body.style.overflow=prev;filterBtnRef.current?.focus()}},[filterOpen]);const [category,setCategory]=useState(search['category']||'');const [gender,setGender]=useState(search['gender']||'');const [sale,setSale]=useState(search['sale']==='true');const [sort,setSort]=useState(sorts.includes(search['sort']??'')?(search['sort'] as string):'Featured');const [maxPrice,setMaxPrice]=useState(()=>{const v=Number(search['maxPrice']);return v>=2000&&v<=10000?v:10000});const [brand,setBrand]=useState(search['brand']||'');const [size,setSize]=useState(Number(search['size'])||0);const [availableOnly,setAvailableOnly]=useState(search['available']==='true');const brands=[...new Set(products.map(p=>p.brand))];
 const q=(search['q']||'').trim().toLowerCase();
 const catOf=(p:Product)=>categories.find(c=>c.id===p.category_id)?.slug||'';
 const pass=(p:Product,ignore:string|null)=>{if(q&&!`${p.name} ${p.brand} ${catOf(p)} ${p.sku}`.toLowerCase().includes(q))return false;if(ignore!=='category'&&category&&catOf(p)!==category)return false;if(ignore!=='gender'&&gender&&!(p.gender===gender||p.gender==='Unisex'))return false;if(ignore!=='brand'&&brand&&p.brand!==brand)return false;if(ignore!=='size'&&size&&!variants.some(v=>v.product_id===p.id&&v.size===size&&v.stock>0))return false;if(ignore!=='sale'&&sale&&!p.compare_at)return false;if(availableOnly&&!variants.some(v=>v.product_id===p.id&&v.stock>0))return false;if(p.price>maxPrice)return false;return true};
 const countFor=(fn:(p:Product)=>boolean)=>products.filter(fn).length;
 const sync=(patch:Record<string,string|undefined>)=>{const next:Record<string,string|undefined>={...search,...patch};for(const k of ['category','gender','brand','size','sale','sort','maxPrice','available'])if(!next[k])delete next[k];if(mode==='shop')navigate({to:'/shop',search:next,replace:true});else navigate({to:'/search',search:next,replace:true})};
 const pick=(setter:(v:string)=>void,key:string)=>(v:string)=>{setter(v);sync({[key]:v||undefined})};
 const setCategorySync=pick(setCategory,'category'),setGenderSync=pick(setGender,'gender'),setBrandSync=pick(setBrand,'brand');
 const setSizeSync=(n:number)=>{setSize(n);sync({size:n?String(n):undefined})};
 const setSortSync=(v:string)=>{setSort(v);sync({sort:v==='Featured'?undefined:v})};
 const setSaleSync=(v:boolean)=>{setSale(v);sync({sale:v?'true':undefined})};
 const setMaxPriceSync=(v:number)=>{setMaxPrice(v);sync({maxPrice:v>=10000?undefined:String(v)})};
 const setAvailableSync=(v:boolean)=>{setAvailableOnly(v);sync({available:v?'true':undefined})};
 const results=useMemo(()=>products.filter(p=>pass(p,null)).sort((a,b)=>sort==='Price: Low to High'?a.price-b.price:sort==='Price: High to Low'?b.price-a.price:sort==='Newest'?Number(b.is_new)-Number(a.is_new):Number(b.featured)-Number(a.featured)),[products,categories,variants,q,category,gender,sale,brand,size,availableOnly,maxPrice,sort]);
 const clear=()=>{setCategory('');setGender('');setSaleSync(false);setMaxPrice(10000);setBrand('');setSize(0);setAvailableOnly(false);const qkeep=search['q']?{q:search['q'] as string}:{};if(mode==='shop')navigate({to:'/shop',search:qkeep,replace:true});else navigate({to:'/search',search:qkeep,replace:true})};
 const filters=<div className="filter-fields"><div className="filter-head"><h3>Filters</h3><Button variant="ghost" onClick={clear}>Clear all</Button></div><div className="filter-group" role="radiogroup" aria-label="Category"><h4>Category</h4><label key="all"><input type="radio" name="f-category" checked={category===""} onChange={()=>setCategorySync("")}/>All</label>{categories.map(c=>{const n=countFor(p=>pass(p,'category')&&catOf(p)===c.slug);return <label key={c.id}><input type="radio" name="f-category" checked={category===c.slug} onChange={()=>setCategorySync(category===c.slug?'':c.slug)}/>{c.name} <span className="filter-count">({n})</span></label>})}</div><div className="filter-group" role="radiogroup" aria-label="Shop by"><h4>Shop by</h4><label key="all"><input type="radio" name="f-gender" checked={gender===""} onChange={()=>setGenderSync("")}/>All</label>{['Men','Women','Kids','Unisex'].map(g=>{const n=countFor(p=>pass(p,'gender')&&(p.gender===g||(g!=='Unisex'&&p.gender==='Unisex')));return <label key={g}><input type="radio" name="f-gender" checked={gender===g} onChange={()=>setGenderSync(gender===g?'':g)}/>{g} <span className="filter-count">({n})</span></label>})}</div><div className="filter-group" role="radiogroup" aria-label="Brand"><h4>Brand</h4><label key="all"><input type="radio" name="f-brand" checked={brand===""} onChange={()=>setBrandSync("")}/>All</label>{brands.map(b=>{const n=countFor(p=>pass(p,'brand')&&p.brand===b);return <label key={b}><input type="radio" name="f-brand" checked={brand===b} onChange={()=>setBrandSync(brand===b?'':b)}/>{b} <span className="filter-count">({n})</span></label>})}</div><div className="filter-group" role="radiogroup" aria-label="Size"><h4>Size (US)</h4><label key="all"><input type="radio" name="f-size" checked={size===0} onChange={()=>setSizeSync(0)}/>All sizes</label>{[6,7,8,9,10,11,12].map(n=>{const c=countFor(p=>pass(p,'size')&&variants.some(v=>v.product_id===p.id&&v.size===n&&v.stock>0));return <label key={n}><input type="radio" name="f-size" checked={size===n} onChange={()=>setSizeSync(size===n?0:n)}/>US {n} <span className="filter-count">({c})</span></label>})}</div><div className="filter-group"><h4>Availability</h4><label><input type="checkbox" checked={availableOnly} onChange={e=>setAvailableSync(e.target.checked)}/>In stock only</label></div><div className="filter-group"><h4>Price up to {`₱${maxPrice.toLocaleString()}`}</h4><input type="range" min="2000" max="10000" step="500" value={maxPrice} onChange={e=>setMaxPriceSync(Number(e.target.value))} className="w-full accent-primary" aria-label={`Maximum price ${maxPrice} pesos`}/></div><div className="filter-group"><h4>Offers</h4><label><input type="checkbox" checked={sale} onChange={e=>setSaleSync(e.target.checked)}/>On sale</label></div></div>;
 return <div className="container-wide page-space"><div className="page-heading"><p className="eyebrow">THE COLLECTION</p><h1>{mode==='search'?(q?`Results for “${search['q']}”`:'Search'):category?categories.find(c=>c.slug===category)?.name:'Find your next favorite'}</h1><p>Cushioned comfort for long days — wear-test any pair for 30 days.</p></div>{mode==='search'&&<form className="mb-8 flex gap-2" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const value=(form.elements.namedItem('q') as HTMLInputElement).value;navigate({to:'/search',search:{q:value}})}}><input name="q" defaultValue={search['q']||''} placeholder="Search products, brands, SKU..." aria-label="Search products" className="h-11 w-full border border-border bg-background px-4"/><Button type="submit" size="lg">Search</Button></form>}
 <div className="shop-layout"><aside className="filter-sidebar">{filters}</aside><div><div className="shop-toolbar"><span aria-live="polite">{results.length} products</span><div className="mobile-filter-actions"><Button variant="outline" ref={filterBtnRef} onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={16}/> Filter</Button></div><label className="sort-control">Sort by <select value={sort} onChange={e=>setSortSync(e.target.value)} aria-label="Sort products">{sorts.map(s=><option key={s}>{s}</option>)}</select><ChevronDown size={14}/></label></div>{results.length?<div className="product-grid">{results.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty-state"><h2>{mode==='search'&&q?`No matches for “${search['q']}”`:'No products found'}</h2>{mode==='search'&&q?<><p>Try a different spelling, or start from a category:</p><p className="empty-links">{categories.slice(0,4).map(c=><Link key={c.id} to="/shop" search={{category:c.slug}}>{c.name}</Link>)}</p><Button variant="outline" onClick={()=>navigate({to:'/shop'})}>Browse everything</Button></>:<><p>Try a different search or clear your filters — new pairs land every week.</p><Button variant="outline" onClick={clear}>Clear filters</Button></>}</div>}</div></div>
 {filterOpen&&<div className="filter-overlay" ref={overlayRef} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Filter products"><div className="filter-overlay-head"><strong>Filter products</strong><Button variant="ghost" size="icon" aria-label="Close filters" onClick={()=>setFilterOpen(false)}><X/></Button></div><div className="filter-overlay-body">{filters}</div><div className="filter-overlay-foot"><Button variant="outline" onClick={clear}>Clear all</Button><Button className="w-full" size="lg" onClick={()=>setFilterOpen(false)}>Show {results.length} products</Button></div></div>}</div>
}
