import { createFileRoute, Link } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { catalogQuery } from '@/lib/catalog-query';
import { images } from '@/lib/catalog';
import { ProductCard } from '@/components/store/ProductCard';
import hero from '@/assets/hero-shoe.jpg';
export const Route=createFileRoute('/')({loader:({context})=>context.queryClient.ensureQueryData(catalogQuery),head:()=>({meta:[{title:'Solehaven — Move With Confidence'},{name:'description',content:'Cushioned runners, everyday sneakers and court classics you can wear-test for 30 days. Free shipping over ₱3,000 at Solehaven.'},{property:'og:title',content:'Solehaven — Move With Confidence'},{property:'og:description',content:'Wear-test comfort for 30 days. Free shipping over ₱3,000.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Home});
function Home(){const {products,categories}=useSuspenseQuery(catalogQuery).data;const arrivals=[...products.filter(p=>p.is_new),...products.filter(p=>!p.is_new&&p.featured)].slice(0,8);return <><section className="home-hero"><img src={hero} alt="Ivory running shoe with red accents" width={1536} height={1024} fetchPriority="high"/><div className="container-wide hero-content"><p className="eyebrow">THE EVERYDAY, REIMAGINED</p><h1>Move with<br/>confidence<span>.</span></h1><p>Cushioned for long days, cut for everyday movement — wear-test any pair for 30 days.</p><div className="hero-buttons"><Button asChild size="lg"><Link to="/shop" search={{gender:'Men'}}>Shop men <ArrowUpRight size={17}/></Link></Button><Button asChild variant="outline" size="lg"><Link to="/shop" search={{gender:'Women'}}>Shop women <ArrowUpRight size={17}/></Link></Button></div><div className="hero-chips">{categories.slice(0,3).map(c=><Link key={c.id} to="/shop" search={{category:c.slug}}>{c.name}</Link>)}<span>30-day wear test · Free returns</span></div></div></section><section className="container-wide category-section"><div className="section-heading-row"><div><p className="eyebrow">FIND YOUR FIT</p><h2 className="section-heading">Explore by category</h2></div><Link to="/categories" className="text-link">View all categories <ArrowRight size={16}/></Link></div><div className="category-grid">{categories.slice(0,6).map(c=><Link key={c.id} to="/shop" search={{category:c.slug}} className="category-tile"><img src={images[c.image_key]} alt={`${c.name} shoes`} width={768} height={768} loading="lazy"/><div><div><h3>{c.name}</h3><span className="tile-meta">{products.filter(p=>p.category_id===c.id).length} styles</span></div><span>Explore <ArrowUpRight size={16}/></span></div></Link>)}</div></section>{arrivals.length>0&&<section className="container-wide arrival-section"><div className="section-heading-row"><div><p className="eyebrow">JUST LANDED</p><h2 className="section-heading">New & noteworthy</h2></div><Link to="/shop" search={{sort:'Newest'}} className="text-link">Shop all <ArrowRight size={16}/></Link></div><div className="product-grid">{arrivals.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}<section className="brand-band"><div className="container-wide"><p className="eyebrow">THE SOLEHAVEN WAY</p><h2>Loved for long days.</h2><p>Cushioned comfort, honest sizing, and a 30-day wear test — free shipping over ₱3,000, easy returns always.</p><Button asChild variant="outline" size="lg"><Link to="/about">Our story <ArrowUpRight size={16}/></Link></Button></div></section></>}
