CREATE TABLE public.categories (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, image_key text not null default 'a1');
GRANT SELECT ON public.categories TO anon, authenticated; GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public categories" ON public.categories FOR SELECT TO anon, authenticated USING (true);
CREATE TABLE public.products (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, brand text not null, category_id uuid references public.categories(id), gender text not null default 'Unisex', description text not null default '', material text not null default 'Mixed materials', price integer not null check (price > 0), compare_at integer check (compare_at > 0), image_key text not null default 'a1', sku text unique not null, featured boolean not null default false, is_new boolean not null default false, archived boolean not null default false, created_at timestamptz not null default now());
GRANT SELECT ON public.products TO anon, authenticated; GRANT INSERT, UPDATE, DELETE ON public.products TO authenticated; GRANT ALL ON public.products TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.user_roles (id uuid primary key default gen_random_uuid(), user_id uuid not null, role text not null check (role in ('admin','user')), unique(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.is_admin(uid uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = uid AND role = 'admin') $$;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;
CREATE POLICY "Read own roles" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Public active products" ON public.products FOR SELECT TO anon, authenticated USING (NOT archived OR public.is_admin(auth.uid()));
CREATE POLICY "Admins insert products" ON public.products FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Admins update products" ON public.products FOR UPDATE TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Admins delete products" ON public.products FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
CREATE TABLE public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, size integer not null check (size between 4 and 15), color text not null, stock integer not null default 0 check (stock >= 0), low_threshold integer not null default 5, unique(product_id,size,color));
GRANT SELECT ON public.product_variants TO anon, authenticated; GRANT INSERT, UPDATE, DELETE ON public.product_variants TO authenticated; GRANT ALL ON public.product_variants TO service_role;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read variants" ON public.product_variants FOR SELECT TO anon, authenticated USING (EXISTS (SELECT 1 FROM public.products p WHERE p.id=product_id));
CREATE POLICY "Admin variant insert" ON public.product_variants FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Admin variant update" ON public.product_variants FOR UPDATE TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Admin variant delete" ON public.product_variants FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
CREATE TABLE public.orders (id uuid primary key default gen_random_uuid(), user_id uuid not null, order_number text unique not null, status text not null default 'Order Placed', payment_method text not null, delivery_method text not null, customer_name text not null, email text not null, phone text not null, address jsonb not null, subtotal integer not null, shipping integer not null, discount integer not null default 0, total integer not null, created_at timestamptz not null default now());
GRANT SELECT ON public.orders TO authenticated; GRANT UPDATE ON public.orders TO authenticated; GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own orders" ON public.orders FOR SELECT TO authenticated USING (user_id=auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "Admin update orders" ON public.orders FOR UPDATE TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE TABLE public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id), variant_id uuid references public.product_variants(id), name text not null, size integer not null, color text not null, quantity integer not null check (quantity > 0), unit_price integer not null);
GRANT SELECT ON public.order_items TO authenticated; GRANT ALL ON public.order_items TO service_role;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read order items" ON public.order_items FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id=order_id AND (o.user_id=auth.uid() OR public.is_admin(auth.uid()))));
CREATE TABLE public.wishlists (user_id uuid not null, product_id uuid not null references public.products(id) on delete cascade, created_at timestamptz default now(), primary key(user_id,product_id));
GRANT SELECT, INSERT, DELETE ON public.wishlists TO authenticated; GRANT ALL ON public.wishlists TO service_role;
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own wishlist" ON public.wishlists FOR SELECT TO authenticated USING (user_id=auth.uid());
CREATE POLICY "Add own wishlist" ON public.wishlists FOR INSERT TO authenticated WITH CHECK (user_id=auth.uid());
CREATE POLICY "Remove own wishlist" ON public.wishlists FOR DELETE TO authenticated USING (user_id=auth.uid());
CREATE TABLE public.reviews (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), user_id uuid not null, rating integer not null check (rating between 1 and 5), body text not null check (length(body) between 1 and 2000), created_at timestamptz not null default now(), unique(product_id,user_id));
GRANT SELECT ON public.reviews TO anon, authenticated; GRANT INSERT ON public.reviews TO authenticated; GRANT ALL ON public.reviews TO service_role;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public reviews" ON public.reviews FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Own reviews" ON public.reviews FOR INSERT TO authenticated WITH CHECK (user_id=auth.uid());
CREATE INDEX products_category_idx ON public.products(category_id); CREATE INDEX products_created_idx ON public.products(created_at DESC); CREATE INDEX variants_product_idx ON public.product_variants(product_id); CREATE INDEX orders_user_idx ON public.orders(user_id,created_at DESC);
CREATE FUNCTION public.place_order(payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE uid uuid := auth.uid(); line jsonb; v record; sub integer := 0; ship integer; total_amount integer; oid uuid; qty integer; addr jsonb; method text; delivery text; BEGIN
IF uid IS NULL THEN RAISE EXCEPTION 'Sign in to place your order'; END IF;
IF jsonb_typeof(payload->'items') != 'array' OR jsonb_array_length(payload->'items') < 1 OR jsonb_array_length(payload->'items') > 30 THEN RAISE EXCEPTION 'Invalid cart'; END IF;
IF length(coalesce(payload->>'name','')) NOT BETWEEN 2 AND 100 OR length(coalesce(payload->>'email','')) NOT BETWEEN 5 AND 255 OR length(coalesce(payload->>'phone','')) NOT BETWEEN 7 AND 30 THEN RAISE EXCEPTION 'Invalid customer details'; END IF;
addr := payload->'address'; IF jsonb_typeof(addr) != 'object' OR length(coalesce(addr->>'street','')) < 3 OR length(coalesce(addr->>'city','')) < 2 OR length(coalesce(addr->>'province','')) < 2 OR length(coalesce(addr->>'barangay','')) < 2 OR length(coalesce(addr->>'postal','')) < 4 THEN RAISE EXCEPTION 'Invalid address'; END IF;
method := payload->>'payment'; delivery := payload->>'delivery'; IF method NOT IN ('Cash on Delivery','Bank Transfer') OR delivery NOT IN ('Standard','Express') THEN RAISE EXCEPTION 'Unsupported payment or delivery'; END IF;
FOR line IN SELECT * FROM jsonb_array_elements(payload->'items') LOOP
qty := (line->>'quantity')::integer; IF qty < 1 OR qty > 10 THEN RAISE EXCEPTION 'Invalid quantity'; END IF;
SELECT pv.id, pv.stock, pv.product_id, pv.size, pv.color, p.name, p.price INTO v FROM public.product_variants pv JOIN public.products p ON p.id=pv.product_id WHERE pv.id=(line->>'variantId')::uuid AND NOT p.archived FOR UPDATE OF pv;
IF NOT FOUND OR v.stock < qty THEN RAISE EXCEPTION 'An item is unavailable in the selected size'; END IF;
sub := sub + v.price * qty;
END LOOP;
ship := CASE WHEN delivery='Express' THEN 300 WHEN sub >= 3000 THEN 0 ELSE 150 END; total_amount := sub + ship;
INSERT INTO public.orders(user_id,order_number,payment_method,delivery_method,customer_name,email,phone,address,subtotal,shipping,total) VALUES (uid,'SH-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)),method,delivery,payload->>'name',payload->>'email',payload->>'phone',addr,sub,ship,total_amount) RETURNING id INTO oid;
FOR line IN SELECT * FROM jsonb_array_elements(payload->'items') LOOP
qty := (line->>'quantity')::integer;
SELECT pv.id,pv.product_id,pv.size,pv.color,p.price,p.name INTO v FROM public.product_variants pv JOIN public.products p ON p.id=pv.product_id WHERE pv.id=(line->>'variantId')::uuid;
UPDATE public.product_variants SET stock=stock-qty WHERE id=v.id;
INSERT INTO public.order_items(order_id,product_id,variant_id,name,size,color,quantity,unit_price) VALUES (oid,v.product_id,v.id,v.name,v.size,v.color,qty,v.price);
END LOOP;
RETURN oid; END $$;
REVOKE ALL ON FUNCTION public.place_order(jsonb) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.place_order(jsonb) TO authenticated;